package models

// Code generated by a tool. DO NOT EDIT.
// Additional custom methods can be implemented in a separate file like <this_file>_ex.go.
// https://sqldalmaker.sourceforge.net/

type Group struct {
	GId   int64  `json:"g_id" gorm:"column:g_id;primary_key;auto_increment"`
	GName string `json:"g_name" gorm:"column:g_name;not null"`
}
