package dbal

// Code generated by a tool. DO NOT EDIT.
// Additional custom methods can be implemented in a separate file like <this_file>_ex.go.
// https://sqldalmaker.sourceforge.net/

import (
	"context"
	"sdm_demo_todolist/raw_sql/dbal/dto"
)

type ProjectsDao struct {
	ds DataStore
}

// (C)RUD: projects
// Generated/AI values are passed to DTO/model.

func (dao *ProjectsDao) CreateProject(ctx context.Context, p *dto.Project) (err error) {
	sql := `insert into projects (p_name) values (?)`
	res, err := dao.ds.Insert(ctx, sql, "p_id", p.PName)
	if err == nil {
		err = assign(&p.PId, res)
	}
	return
}

// C(R)UD: projects

func (dao *ProjectsDao) ReadProject(ctx context.Context, pId int64) (res *dto.Project, err error) {
	sql := `select * from projects where p_id=?`
	res = &dto.Project{}
	_fa := []interface{}{
		&res.PId,
		&res.PName,
	}
	err = dao.ds.QueryByFA(ctx, sql, _fa, pId)
	return
}

// CR(U)D: projects

func (dao *ProjectsDao) UpdateProject(ctx context.Context, p *dto.Project) (rowsAffected int64, err error) {
	sql := `update projects set p_name=? where p_id=?`
	rowsAffected, err = dao.ds.Exec(ctx, sql, p.PName, p.PId)
	return
}

// CRU(D): projects

func (dao *ProjectsDao) DeleteProject(ctx context.Context, p *dto.Project) (rowsAffected int64, err error) {
	sql := `delete from projects where p_id=?`
	rowsAffected, err = dao.ds.Exec(ctx, sql, p.PId)
	return
}

func (dao *ProjectsDao) GetProjectList(ctx context.Context) (res []*dto.Project, err error) {
	sql := `select p.*, 
		(select count(*) from tasks where p_id=p.p_id) as p_tasks_count 
		from projects p 
		order by p.p_id`
	_onRow := func() (interface{}, func()) {
		_obj := &dto.Project{}
		return []interface{}{
				&_obj.PId,
				&_obj.PName,
				&_obj.PTasksCount,
			}, func() {
				res = append(res, _obj)
			}
	}
	err = dao.ds.QueryAllByFA(ctx, sql, _onRow)
	return
}

func (dao *ProjectsDao) GetProjectIds(ctx context.Context) (res []int64, err error) {
	sql := `select p.*, 
		(select count(*) from tasks where p_id=p.p_id) as p_tasks_count 
		from projects p 
		order by p.p_id`
	errMap := make(map[string]int)
	onRow := func(val interface{}) {
		var data int64
		fromVal(&data, val, errMap)
		res = append(res, data)
	}
	err = dao.ds.QueryAll(ctx, sql, onRow)
	if err == nil {
		err = errMapToErr(errMap)
	}
	return
}

func (dao *ProjectsDao) GetProjectId(ctx context.Context) (res int64, err error) {
	sql := `select p.*, 
		(select count(*) from tasks where p_id=p.p_id) as p_tasks_count 
		from projects p 
		order by p.p_id`
	r, err := dao.ds.Query(ctx, sql)
	if err == nil {
		err = assign(&res, r)
	}
	return
}
